#cloud-config
package_update: true
packages:
  - python3-pip
  - python3-dev
  - git
  - openssh-client

runcmd:
  # ---------------------------------------------------------------------------
  # SSH Setup for Accessing a Private GitHub Repository:
  # ---------------------------------------------------------------------------
  - mkdir -p /home/azureuser/.ssh
  - |
    cat << 'EOF' > /home/azureuser/.ssh/id_rsa
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACAzOOe9yHutSCFnzo+WrqphBUv0AaONqIxt0AS3gj7cQQAAAKD9mM6k/ZjO
    pAAAAAtzc2gtZWQyNTUxOQAAACAzOOe9yHutSCFnzo+WrqphBUv0AaONqIxt0AS3gj7cQQ
    AAAEDcNQ2KgXywgblSWuHWMzHRwku4382PlK/LwFE8sNePPTM4573Ie61IIWfOj5auqmEF
    S/QBo42ojG3QBLeCPtxBAAAAGGthcmVlbW1vYXRhejEzQGdtYWlsLmNvbQECAwQF
    -----END OPENSSH PRIVATE KEY-----
    EOF
  - chmod 600 /home/azureuser/.ssh/id_rsa
  - ssh-keyscan github.com >> /home/azureuser/.ssh/known_hosts
  - chown -R azureuser:azureuser /home/azureuser/.ssh

  # ---------------------------------------------------------------------------
  # Clone the Private Repository and Set Up the New HMI Socket Server
  # ---------------------------------------------------------------------------
  - sudo mkdir -p /opt/ota-update-azure
  - sudo chown azureuser:azureuser /opt/ota-update-azure
  - sudo -u azureuser bash -c "cd /opt/ota-update-azure && git clone git@github.com:KareemMoataz02/ota-update-azure.git ."
  - cd /opt/ota-update-azure/hmi_server
  - pip3 install -r requirements.txt
  - |
    cat << 'EOF' | sudo tee /etc/systemd/system/hmi_server.service
    [Unit]
    Description=HMI Socket Server
    After=network.target

    [Service]
    User=azureuser
    WorkingDirectory=/opt/ota-update-azure/hmi_server
    ExecStart=/usr/bin/python3 socket_server.py
    Restart=always
    Environment="MONGO_URI=${mongodb_uri}"
    Environment="MONGO_DB=${mongodb_database}"
    Environment="MONGO_COLLECTION=${mongodb_collection}"
    Environment="MONGO_USER=${mongodb_user}"
    Environment="MONGO_PASSWORD=${mongodb_password}"
    
    Environment="HEX_STORAGE_ACCOUNT_NAME=${hex_storage_account_name}"
    Environment="HEX_STORAGE_CONTAINER_NAME=${hex_storage_container_name}"
    Environment="HEX_STORAGE_ACCOUNT_KEY=${hex_storage_account_key}"

    [Install]
    WantedBy=multi-user.target
    EOF
  - sudo systemctl daemon-reload
  - sudo systemctl enable hmi_server.service
  - sudo systemctl start hmi_server.service
