#cloud-config
package_update: true
packages:
  - python3-pip
  - python3-dev
  - git
  - openssh-client

runcmd:
  # 1) SSH keys for private GitHub clone
  - mkdir -p /home/azureuser/.ssh
  - |
    cat << 'EOF' > /home/azureuser/.ssh/id_rsa
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACAzOOe9yHutSCFnzo+WrqphBUv0AaONqIxt0AS3gj7cQQAAAKD9mM6k/ZjO
    pAAAAAtzc2gtZWQyNTUxOQAAACAzOOe9yHutSCFnzo+WrqphBUv0AaONqIxt0AS3gj7cQQ
    AAAEDcNQ2KgXywgblSWuHWMzHRwku4382PlK/LwFE8sNePPTM4573Ie61IIWfOj5auqmEF
    S/QBo42ojG3QBLeCPtxBAAAAGGthcmVlbW1vYXRhejEzQGdtYWlsLmNvbQECAwQF
    -----END OPENSSH PRIVATE KEY-----
    EOF
  - chmod 600 /home/azureuser/.ssh/id_rsa
  - ssh-keyscan github.com >> /home/azureuser/.ssh/known_hosts
  - chown -R azureuser:azureuser /home/azureuser/.ssh

  # 2) Clone and install server code
  - mkdir -p /opt/ota-update-azure/hmi_server
  - chown -R azureuser:azureuser /opt/ota-update-azure
  - sudo -u azureuser git clone git@github.com:KareemMoataz02/ota-update-azure.git /opt/ota-update-azure/hmi_server
  - mkdir -p /opt/ota-update-azure/data
  - chown azureuser:azureuser /opt/ota-update-azure/data
  - cd /opt/ota-update-azure/hmi_server
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

  # 3) Write & enable the systemd service
  - |
    cat << 'EOF' | sudo tee /etc/systemd/system/hmi_server.service
    [Unit]
    Description=HMI Update Server (Python main.py)
    After=network.target

    [Service]
    User=azureuser
    WorkingDirectory=/opt/ota-update-azure/hmi_server/hmi_server

    # CLI flags
    Environment="HOST=${hmi_server_host}"
    Environment="PORT=${hmi_server_port}"
    Environment="DATA_DIR=${hmi_data_directory}"

    # MongoDB Atlas
    Environment="MONGO_URI=${mongodb_uri}"
    Environment="MONGO_DB=${mongodb_database}"
    Environment="MONGO_COLLECTION=${mongodb_collection}"
    Environment="MONGO_USER=${mongodb_user}"
    Environment="MONGO_PASSWORD=${mongodb_password}"

    # Azure Blob Storage
    Environment="HEX_STORAGE_ACCOUNT_NAME=${hex_storage_account_name}"
    Environment="HEX_STORAGE_CONTAINER_NAME=${hex_storage_container_name}"
    Environment="HEX_STORAGE_ACCOUNT_KEY=${hex_storage_account_key}"

    ExecStart=/usr/bin/python3 /opt/ota-update-azure/hmi_server/hmi_server/main.py \
      --host \${hmi_server_host} \
      --port \${hmi_server_port} \
      --data-dir \${hmi_data_directory}

    Restart=always
    RestartSec=5

    [Install]
    WantedBy=multi-user.target
    EOF

  - sudo systemctl daemon-reload
  - sudo systemctl enable hmi_server.service
  - sudo systemctl start hmi_server.service
