#cloud-config
package_update: true
package_upgrade: true
packages:
  - python3-venv
  - python3-pip
  - python3-setuptools
  - python3-distutils
  - git
  - openssh-client

runcmd:
  # 1) SSH key setup for private repo
  - mkdir -p /home/azureuser/.ssh
  - |
    cat << 'EOF' > /home/azureuser/.ssh/id_rsa
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACAzOOe9yHutSCFnzo+WrqphBUv0AaONqIxt0AS3gj7cQQAAAKD9mM6k/ZjO
    pAAAAAtzc2gtZWQyNTUxOQAAACAzOOe9yHutSCFnzo+WrqphBUv0AaONqIxt0AS3gj7cQQ
    AAAEDcNQ2KgXywgblSWuHWMzHRwku4382PlK/LwFE8sNePPTM4573Ie61IIWfOj5auqmEF
    S/QBo42ojG3QBLeCPtxBAAAAGGthcmVlbW1vYXRhejEzQGdtYWlsLmNvbQECAwQF
    -----END OPENSSH PRIVATE KEY-----
    EOF
  - chmod 600 /home/azureuser/.ssh/id_rsa
  - ssh-keyscan github.com >> /home/azureuser/.ssh/known_hosts
  - chown -R azureuser:azureuser /home/azureuser/.ssh

  # 2) Clone your repo
  - mkdir -p /opt/ota-update-azure
  - chown azureuser:azureuser /opt/ota-update-azure
  - sudo -u azureuser -H git clone git@github.com:KareemMoataz02/ota-update-azure.git /opt/ota-update-azure/hmi_server

  # 3) Create & activate a venv to isolate dependencies
  - python3 -m venv /opt/ota-update-azure/env
  - chown -R azureuser:azureuser /opt/ota-update-azure/env

  # 4) Install Python deps inside the venv
  - /opt/ota-update-azure/env/bin/pip install --upgrade pip
  - /opt/ota-update-azure/env/bin/pip install -r /opt/ota-update-azure/hmi_server/requirements.txt
  - /opt/ota-update-azure/env/bin/pip install python-dotenv dataclasses "pymongo[srv]" dnspython requests certifi azure-storage-blob azure-identity
  # 5) Prepare data directory
  - mkdir -p /opt/ota-update-azure/data
  - chown azureuser:azureuser /opt/ota-update-azure/data

  # 6) Drop in systemd unit for your HMI server
  - |
    cat << 'EOF' | sudo tee /etc/systemd/system/hmi_server.service
    [Unit]
    Description=HMI Update Server (Python main.py)
    After=network-online.target
    Wants=network-online.target

    [Service]
    Type=simple
    User=azureuser
    WorkingDirectory=/opt/ota-update-azure/hmi_server/hmi_server

    Environment="HOST=${hmi_server_host}"
    Environment="PORT=${hmi_server_port}"
    Environment="DATA_DIR=${hmi_data_directory}"

    Environment="MONGO_URI=${mongodb_uri}"
    Environment="MONGO_DB=${mongodb_database}"
    Environment="MONGO_COLLECTION=${mongodb_collection}"
    Environment="MONGO_USER=${mongodb_user}"
    Environment="MONGO_PASSWORD=${mongodb_password}"

    Environment="HEX_STORAGE_ACCOUNT_NAME=${hex_storage_account_name}"
    Environment="HEX_STORAGE_CONTAINER_NAME=${hex_storage_container_name}"
    Environment="HEX_STORAGE_ACCOUNT_KEY=${hex_storage_account_key}"
  
    ExecStart=/opt/ota-update-azure/env/bin/python /opt/ota-update-azure/hmi_server/hmi_server/main.py \
      --host $HOST \
      --port $PORT \
      --data-dir $DATA_DIR


    Restart=always
    RestartSec=5

    [Install]
    WantedBy=multi-user.target
    EOF

  # 7) Enable and start your service
  - sudo systemctl daemon-reload
  - sudo systemctl enable hmi_server.service
  - sudo systemctl start hmi_server.service
