#cloud-config
package_update: true
packages:
  - python3-pip
  - python3-dev
  - git
  - curl

runcmd:
  # ------------------------------------------------------------
  # 1) Clone & install your HMI server code
  # ------------------------------------------------------------
  - mkdir -p /opt/ota-update-azure
  - chown azureuser:azureuser /opt/ota-update-azure
  - sudo -u azureuser bash -lc "git clone git@github.com:KareemMoataz02/ota-update-azure.git /opt/ota-update-azure"
  - cd /opt/ota-update-azure/hmi_server
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

  # ------------------------------------------------------------
  # 2) Write the systemd unit
  # ------------------------------------------------------------
  - |
    cat << 'EOF' | sudo tee /etc/systemd/system/hmi_server.service
    [Unit]
    Description=HMI Update Server (Python main.py)
    After=network.target

    [Service]
    User=azureuser
    WorkingDirectory=/opt/ota-update-azure/hmi_server

    # CLI-flags (from your Terraform custom_data)
    Environment="HOST=${hmi_server_host}"
    Environment="PORT=${hmi_server_port}"
    Environment="DATA_DIR=${hmi_data_directory}"

    # Atlas / Hex Storage
    Environment="MONGO_URI=${mongodb_uri}"
    Environment="MONGO_USER=${mongodb_user}"
    Environment="MONGO_PASSWORD=${mongodb_password}"
    Environment="MONGO_DB=${mongodb_database}"
    Environment="MONGO_COLLECTION=${mongodb_collection}"
    Environment="HEX_STORAGE_ACCOUNT_NAME=${hex_storage_account_name}"
    Environment="HEX_STORAGE_CONTAINER_NAME=${hex_storage_container_name}"
    Environment="HEX_STORAGE_ACCOUNT_KEY=${hex_storage_account_key}"

    ExecStart=/usr/bin/python3 /opt/ota-update-azure/hmi_server/main.py \
      --host ${HOST} \
      --port ${PORT} \
      --data-dir ${DATA_DIR}

    Restart=always
    RestartSec=5

    [Install]
    WantedBy=multi-user.target
    EOF

  # ------------------------------------------------------------
  # 3) Enable & start
  # ------------------------------------------------------------
  - sudo systemctl daemon-reload
  - sudo systemctl enable hmi_server.service
  - sudo systemctl start hmi_server.service
