version: "3.8"
services:

  frontend:
    build:
      context: .
      dockerfile: website_app/frontend/DockerFile
      args:
        REACT_APP_API_URL: http://backend:80/api
    image: kareemmoataz13/ota-frontend:latest
    ports:
      - "80:80"

  backend:
    build:
      context: .
      dockerfile: website_app/backend_server/DockerFile
    image: kareemmoataz13/ota-backend:latest
    environment:
      COSMOSDB_URI:        ${COSMOSDB_URI}
      COSMOSDB_DATABASE:   ${COSMOSDB_DATABASE}
      COSMOSDB_COLLECTION: ${COSMOSDB_COLLECTION}
      COSMOSDB_KEY:        ${COSMOSDB_KEY}
      HEX_STORAGE_ACCOUNT_NAME:   ${HEX_STORAGE_ACCOUNT_NAME}
      HEX_STORAGE_CONTAINER_NAME: ${HEX_STORAGE_CONTAINER_NAME}
      HEX_STORAGE_ACCOUNT_KEY:    ${HEX_STORAGE_ACCOUNT_KEY}
    expose:
      - "80"