version: "3.8"

services:

  frontend:
    build:
      context: ./website_app/frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: https://ota-website-app.azurewebsites.net/api
    image: kareemmoataz13/ota-frontend:latest
    ports:
      - "80:80"

  backend:
    build:
      context: ./website_app/backend_server
      dockerfile: Dockerfile
    image: kareemmoataz13/ota-backend:latest
    environment:
      # your COSMOS/HEX vars…
      COSMOSDB_URI:        ${COSMOSDB_URI}
      COSMOSDB_DATABASE:   ${COSMOSDB_DATABASE}
      COSMOSDB_COLLECTION: ${COSMOSDB_COLLECTION}
      COSMOSDB_KEY:        ${COSMOSDB_KEY}
      HEX_STORAGE_ACCOUNT_NAME:   ${HEX_STORAGE_ACCOUNT_NAME}
      HEX_STORAGE_CONTAINER_NAME: ${HEX_STORAGE_CONTAINER_NAME}
      HEX_STORAGE_ACCOUNT_KEY:    ${HEX_STORAGE_ACCOUNT_KEY}
    expose:
      - "80"
