name: CI/CD OTA Update Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      website_changed: ${{ steps.filter.outputs.website }}
    steps:
      - uses: actions/checkout@v3
      - name: Filter website_app changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            website:
              - 'website_app/**'

  docker-build:
    needs: filter
    if: needs.filter.outputs.website_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push website_app image
        run: |
          docker build -t kareemmoataz13/ota-website-app:latest website_app/
          docker push kareemmoataz13/ota-website-app:latest

  terraform-deploy:
    runs-on: ubuntu-latest
    needs: filter
    if: always()
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure CLI Login
        run: |
          az login --service-principal \
            -u ${{ secrets.ARM_CLIENT_ID }} \
            -p ${{ secrets.ARM_CLIENT_SECRET }} \
            --tenant ${{ secrets.ARM_TENANT_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -migrate-state

      - name: Terraform unlock
        working-directory: terraform
        run: terraform force-unlock bc5c552d-ca9e-84b7-dabf-e6c0ffedd77f -auto-approve

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
